#!/usr/bin/env bash
#=> このシェルスクリプトが存在しているフォルダの絶対パス
THIS_DIR="$(cd $(dirname $0);pwd)" 

#=> 一つ上を経由したbinフォルダのパスをクラスパスに追加
export CLASSPATH="${THIS_DIR}/../bin" 

# このシェルスクリプトの入力引数をJavaアプリに渡す
java mypkg.HelloJava "$@"